[tools]
trunk = "1.3.4"
node = "24.13.1"

[tasks]
install = 'sh scripts/install.sh'
lint = 'trunk check --ci'
fmt = 'trunk fmt'
"test:compile" = 'sh scripts/build.sh'
test = { depends = ["test:*"] }
codegen = 'echo "No codegen"'
ci = { depends = ["lint", "test"] }
