name: Autorelease

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request: {}
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  autorelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v2
        with:
          version: 2024.11.8

      - run: mise run install
      - run: mise run codegen

      - name: Check for changes
        id: git-check
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Create PR if changes
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update generated code"
          title: "chore: update generated code"
          body: This PR updates generated code.
          branch: chore/codegen-update

      - run: mise run ci

      - name: Release
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} --generate-notes --title "Release ${{ github.ref_name }}" || true

      - name: Upload Artifacts
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: main-binary
          path: main
